### PR TITLE
Further README fixes

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

**Comment by alekseykulikov** [comment]
Please, push all your 3 readme PRs to treojs, they are awesome :)
Thanks!

**Comment by brettz9** [comment]
Thank you, but I did submit them, though as separate PRs (and I only have two branches)--are u saying u want them as one PR?

**Comment by alekseykulikov** [comment]
No, just submit them to original treojs/idb-batch, not brettz9/idb-batch :)
I haven't seem them, and only found after checking your Github profile.

**Comment by brettz9** [comment]
Oh, sheesh, whoops

**Pull request closed without merging**
